# Generated by Django 5.2.17 on 2026-09-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="creado el"),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="actualizado el"),
        ),
    ]
