# Generated by Django 5.2.17 on 2026-09-25 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_activity"),
    ]

    operations = [
        migrations.CreateModel(
            name="RateLimitBucket",
            fields=[
                ("key", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("count", models.PositiveIntegerField()),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
        ),
    ]
