# Generated by Django 5.2.17 on 2026-09-19 19:34

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("forms", "0004_alter_fieldoption_options_alter_formfield_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Recibida"),
                            ("UNDER_REVIEW", "En revisión"),
                            ("VALIDATED", "Validada"),
                            ("REJECTED", "Rechazada"),
                        ],
                        default="SUBMITTED",
                        max_length=16,
                        verbose_name="estado",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="fecha de envío",
                    ),
                ),
                ("idempotency_key", models.UUIDField(editable=False, unique=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to="forms.form",
                        verbose_name="formulario",
                    ),
                ),
                (
                    "form_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to="forms.formversion",
                        verbose_name="versión",
                    ),
                ),
            ],
            options={
                "verbose_name": "respuesta",
                "verbose_name_plural": "respuestas",
                "ordering": ["-submitted_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SubmissionAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("value", models.JSONField(blank=True, null=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="forms.formfield"
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="answers",
                        to="submissions.submission",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["form", "submitted_at"], name="submissions_form_id_0c53c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["form", "status"], name="submissions_form_id_76347b_idx"),
        ),
        migrations.AddConstraint(
            model_name="submission",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["SUBMITTED", "UNDER_REVIEW", "VALIDATED", "REJECTED"])
                ),
                name="submission_valid_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="submissionanswer",
            constraint=models.UniqueConstraint(
                fields=("submission", "field"), name="one_answer_per_submission_field"
            ),
        ),
    ]
