# Generated by Django 5.2.17 on 2026-09-19 23:39

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.submissions.storage


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=300,
                        storage=apps.submissions.storage.response_file_storage,
                        upload_to=apps.submissions.storage.response_file_path,
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("size", models.PositiveBigIntegerField()),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="files",
                        to="submissions.submissionanswer",
                    ),
                ),
            ],
        ),
    ]
