# Generated by Django 5.2.17 on 2026-09-24 01:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0002_submissionfile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="review_revision",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.CreateModel(
            name="SubmissionReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Recibida"),
                            ("UNDER_REVIEW", "En revisión"),
                            ("VALIDATED", "Validada"),
                            ("REJECTED", "Rechazada"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Recibida"),
                            ("UNDER_REVIEW", "En revisión"),
                            ("VALIDATED", "Validada"),
                            ("REJECTED", "Rechazada"),
                        ],
                        max_length=16,
                    ),
                ),
                ("note", models.TextField(blank=True, max_length=2000, verbose_name="comentario")),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="submissions.submission",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "REJECTED"), _negated=True),
                            models.Q(("note", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="rejected_review_has_reason",
                    )
                ],
            },
        ),
    ]
