# Generated by Django 5.2.17 on 2026-09-24 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0003_submission_review_revision_submissionreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="attention",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Sin incidencias"),
                    ("ATTENTION", "Requiere atención"),
                    ("ILLEGIBLE", "Documento ilegible"),
                    ("INCOMPLETE", "Incompleta"),
                    ("DUPLICATE", "Duplicado"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="attention_note",
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
