# Generated by Django 5.2.17 on 2026-09-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0007_alter_submission_options_alter_submission_managers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingFileDeletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=300, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
