# Generated by Django 5.2.17 on 2026-09-19 18:00

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.forms.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="nombre")),
                ("slug", models.SlugField(max_length=180)),
                ("description", models.TextField(blank=True, verbose_name="descripción")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Borrador"),
                            ("PUBLISHED", "Publicado"),
                            ("PAUSED", "Pausado"),
                            ("ARCHIVED", "Archivado"),
                        ],
                        default="DRAFT",
                        max_length=12,
                        verbose_name="estado",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="accounts.workspace"
                    ),
                ),
            ],
            options={
                "verbose_name": "formulario",
                "verbose_name_plural": "formularios",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="FormVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("version_number", models.PositiveIntegerField(verbose_name="versión")),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Borrador"), ("PUBLISHED", "Publicada")],
                        default="DRAFT",
                        max_length=12,
                        verbose_name="estado",
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("schema_version", models.PositiveIntegerField(default=1)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="forms.form",
                    ),
                ),
            ],
            options={
                "verbose_name": "versión",
                "verbose_name_plural": "versiones",
                "ordering": ["form", "-version_number"],
            },
        ),
        migrations.CreateModel(
            name="FormSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="título")),
                ("description", models.TextField(blank=True, verbose_name="descripción")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="orden")),
                (
                    "configuration",
                    models.JSONField(
                        blank=True, default=dict, validators=[apps.forms.models.validate_object]
                    ),
                ),
                (
                    "form_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="forms.formversion",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="FormField",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "stable_key",
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-z][a-z0-9_]*$", "Usa letras minúsculas, números y guion bajo."
                            )
                        ],
                    ),
                ),
                ("label", models.CharField(max_length=240, verbose_name="etiqueta")),
                ("help_text", models.TextField(blank=True, verbose_name="ayuda")),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("SHORT_TEXT", "Texto corto"),
                            ("LONG_TEXT", "Texto largo"),
                            ("EMAIL", "Correo electrónico"),
                            ("PHONE", "Teléfono"),
                            ("NUMBER", "Número"),
                            ("DATE", "Fecha"),
                            ("SINGLE_CHOICE", "Selección única"),
                            ("MULTIPLE_CHOICE", "Selección múltiple"),
                            ("BOOLEAN", "Sí / No"),
                            ("FILE", "Archivo"),
                            ("DOCUMENT", "Documento"),
                            ("HEADING", "Encabezado"),
                            ("INFORMATION", "Información"),
                        ],
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                ("required", models.BooleanField(default=False, verbose_name="obligatorio")),
                ("placeholder", models.CharField(blank=True, max_length=240)),
                ("order", models.PositiveIntegerField(default=0, verbose_name="orden")),
                (
                    "configuration",
                    models.JSONField(
                        blank=True, default=dict, validators=[apps.forms.models.validate_object]
                    ),
                ),
                (
                    "validation",
                    models.JSONField(
                        blank=True, default=dict, validators=[apps.forms.models.validate_object]
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="forms.formsection",
                    ),
                ),
                (
                    "form_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="forms.formversion",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="form",
            name="active_version",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="active_for_forms",
                to="forms.formversion",
            ),
        ),
        migrations.CreateModel(
            name="ConditionalRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("EQUALS", "Igual a"),
                            ("NOT_EQUALS", "Distinto de"),
                            ("CONTAINS", "Contiene"),
                            ("GREATER_THAN", "Mayor que"),
                            ("LESS_THAN", "Menor que"),
                            ("IS_EMPTY", "Está vacío"),
                            ("IS_NOT_EMPTY", "No está vacío"),
                        ],
                        max_length=20,
                    ),
                ),
                ("expected_value", models.JSONField(blank=True, null=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("SHOW", "Mostrar"),
                            ("HIDE", "Ocultar"),
                            ("REQUIRE", "Hacer obligatorio"),
                            ("OPTIONAL", "Hacer opcional"),
                        ],
                        max_length=12,
                    ),
                ),
                ("group", models.PositiveIntegerField(default=0)),
                (
                    "combinator",
                    models.CharField(
                        choices=[("AND", "Todas"), ("OR", "Alguna")], default="AND", max_length=3
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "source_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_rules",
                        to="forms.formfield",
                    ),
                ),
                (
                    "target_field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_rules",
                        to="forms.formfield",
                    ),
                ),
                (
                    "target_section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_rules",
                        to="forms.formsection",
                    ),
                ),
                (
                    "form_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="forms.formversion",
                    ),
                ),
            ],
            options={
                "ordering": ["group", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="FieldOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("label", models.CharField(max_length=240, verbose_name="etiqueta")),
                ("value", models.CharField(max_length=150, verbose_name="valor")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="orden")),
                ("is_active", models.BooleanField(default=True, verbose_name="activa")),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="forms.formfield",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "constraints": [
                    models.UniqueConstraint(fields=("field", "value"), name="option_field_value")
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="formversion",
            constraint=models.UniqueConstraint(
                fields=("form", "version_number"), name="form_version_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="formversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "DRAFT")), fields=("form",), name="one_draft_per_form"
            ),
        ),
        migrations.AddConstraint(
            model_name="formversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("schema_version__gte", 1), ("version_number__gte", 1)),
                name="positive_version_numbers",
            ),
        ),
        migrations.AddConstraint(
            model_name="formversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("published_at__isnull", True), ("status", "DRAFT")),
                    models.Q(("published_at__isnull", False), ("status", "PUBLISHED")),
                    _connector="OR",
                ),
                name="version_publication_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="formfield",
            constraint=models.UniqueConstraint(
                fields=("form_version", "stable_key"), name="field_key_per_version"
            ),
        ),
        migrations.AddIndex(
            model_name="form",
            index=models.Index(
                fields=["workspace", "status"], name="forms_form_workspa_60c64e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="form",
            constraint=models.UniqueConstraint(
                fields=("workspace", "slug"), name="form_workspace_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="form",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["DRAFT", "PUBLISHED", "PAUSED", "ARCHIVED"])),
                name="form_valid_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="form",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "PUBLISHED"), _negated=True),
                    ("active_version__isnull", False),
                    _connector="OR",
                ),
                name="published_form_has_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="conditionalrule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("target_field__isnull", False), ("target_section__isnull", True)),
                    models.Q(("target_field__isnull", True), ("target_section__isnull", False)),
                    _connector="OR",
                ),
                name="rule_exactly_one_target",
            ),
        ),
    ]
