# Generated by Django 5.2.17 on 2026-09-19 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_spanish_admin_labels"),
        ("forms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="active_version",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="active_for_forms",
                to="forms.formversion",
                verbose_name="versión activa",
            ),
        ),
        migrations.AlterField(
            model_name="form",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="creado el"),
        ),
        migrations.AlterField(
            model_name="form",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="creado por",
            ),
        ),
        migrations.AlterField(
            model_name="form",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="actualizado el"),
        ),
        migrations.AlterField(
            model_name="form",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.workspace",
                verbose_name="espacio de trabajo",
            ),
        ),
        migrations.AlterField(
            model_name="formversion",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="creada el"),
        ),
        migrations.AlterField(
            model_name="formversion",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="publicada el"),
        ),
        migrations.AlterField(
            model_name="formversion",
            name="schema_version",
            field=models.PositiveIntegerField(default=1, verbose_name="versión del esquema"),
        ),
    ]
