# Generated by Django 5.2.17 on 2026-09-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0003_rule_group_names"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fieldoption",
            options={
                "ordering": ["order", "id"],
                "verbose_name": "opción",
                "verbose_name_plural": "opciones",
            },
        ),
        migrations.AlterModelOptions(
            name="formfield",
            options={
                "ordering": ["order", "id"],
                "verbose_name": "campo",
                "verbose_name_plural": "campos",
            },
        ),
        migrations.AlterModelOptions(
            name="formsection",
            options={
                "ordering": ["order", "id"],
                "verbose_name": "sección",
                "verbose_name_plural": "secciones",
            },
        ),
        migrations.RemoveConstraint(
            model_name="formversion",
            name="version_publication_consistent",
        ),
        migrations.AlterField(
            model_name="formversion",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Borrador"),
                    ("PUBLISHED", "Publicada"),
                    ("ARCHIVED", "Archivada"),
                ],
                default="DRAFT",
                max_length=12,
                verbose_name="estado",
            ),
        ),
        migrations.AddIndex(
            model_name="conditionalrule",
            index=models.Index(
                fields=["form_version", "order"], name="forms_condi_form_ve_3fb79f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fieldoption",
            index=models.Index(fields=["field", "order"], name="forms_field_field_i_31886d_idx"),
        ),
        migrations.AddIndex(
            model_name="formfield",
            index=models.Index(fields=["section", "order"], name="forms_formf_section_2c7ebd_idx"),
        ),
        migrations.AddIndex(
            model_name="formsection",
            index=models.Index(
                fields=["form_version", "order"], name="forms_forms_form_ve_c66c01_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="formversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("published_at__isnull", True), ("status", "DRAFT")),
                    models.Q(("published_at__isnull", False), ("status", "PUBLISHED")),
                    ("status", "ARCHIVED"),
                    _connector="OR",
                ),
                name="version_publication_consistent",
            ),
        ),
    ]
