# Generated by Django 5.2.17 on 2026-09-19 20:09

import uuid

import django.db.models.deletion
from django.db import migrations, models


def snapshot_published_titles(apps, schema_editor):
    version_model = apps.get_model("forms", "FormVersion")
    for version in version_model.objects.exclude(status="DRAFT").select_related("form").iterator():
        version_model.objects.filter(pk=version.pk).update(
            title=version.form.name, description=version.form.description
        )


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0004_alter_fieldoption_options_alter_formfield_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="formversion",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="formversion",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.RunPython(snapshot_published_titles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="formfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("SHORT_TEXT", "Texto corto"),
                    ("LONG_TEXT", "Texto largo"),
                    ("EMAIL", "Correo electrónico"),
                    ("PHONE", "Teléfono"),
                    ("NUMBER", "Número"),
                    ("DATE", "Fecha"),
                    ("SINGLE_CHOICE", "Selección única"),
                    ("MULTIPLE_CHOICE", "Selección múltiple"),
                    ("BOOLEAN", "Sí / No"),
                    ("FILE", "Archivo"),
                    ("DOCUMENT", "Documento"),
                    ("HEADING", "Encabezado"),
                    ("INFORMATION", "Información"),
                    ("IMAGE", "Imagen"),
                ],
                max_length=20,
                verbose_name="tipo",
            ),
        ),
        migrations.CreateModel(
            name="FormImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("file", models.FileField(upload_to="form-images/%Y/%m/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="forms.form",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="formfield",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="forms.formimage",
            ),
        ),
    ]
