# Generated by Django 5.2.17 on 2026-09-20 00:21

import django.db.models.deletion
from django.db import migrations, models

import apps.forms.models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0007_alter_formfield_field_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="formversion",
            name="welcome",
            field=models.JSONField(
                blank=True, default=dict, validators=[apps.forms.models.validate_object]
            ),
        ),
        migrations.AddField(
            model_name="formversion",
            name="welcome_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="welcome_versions",
                to="forms.formimage",
            ),
        ),
    ]
