# Generated by Django 5.2.17 on 2026-09-20 00:31

import apps.forms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_formversion_welcome_formversion_welcome_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='formversion',
            name='appearance',
            field=models.JSONField(blank=True, default=dict, validators=[apps.forms.models.validate_object]),
        ),
    ]
