# Generated by Django 5.2.17 on 2026-09-22 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0009_formversion_appearance"),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldoption",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="options",
                to="forms.formimage",
                verbose_name="imagen de la opción",
            ),
        ),
    ]
