# Generated by Django 5.2.17 on 2026-09-24 02:17

from django.db import migrations, models

import apps.forms.models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0010_fieldoption_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="response_summary",
            field=models.JSONField(
                blank=True, default=dict, validators=[apps.forms.models.validate_object]
            ),
        ),
    ]
