# Generated by Django 5.2.17 on 2026-09-25 23:20

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("forms", "0011_form_response_summary"),
        ("submissions", "0008_pendingfiledeletion"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailSuppression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("reason", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="EmailNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("form_name", models.CharField(max_length=200)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("SUBMISSION_RECEIVED", "Nueva respuesta"),
                            ("SUBMISSION_VALIDATED", "Solicitud aprobada"),
                            ("SUBMISSION_REJECTED", "Solicitud rechazada"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "recipient_kind",
                    models.CharField(
                        choices=[("INTERNAL", "Interno"), ("RESPONDENT", "Respondiente")],
                        max_length=12,
                    ),
                ),
                ("recipient_email", models.EmailField(blank=True, db_index=True, max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("SENDING", "En proceso"),
                            ("SENT", "Enviado"),
                            ("DELIVERED", "Entregado"),
                            ("DELIVERY_DELAYED", "Entrega demorada"),
                            ("FAILED", "Fallido"),
                            ("BOUNCED", "Rebotado"),
                            ("COMPLAINED", "Marcado como spam"),
                            ("SUPPRESSED", "Suprimido"),
                            ("SKIPPED", "Omitido"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=300)),
                ("provider", models.CharField(default="resend", max_length=20)),
                (
                    "provider_message_id",
                    models.CharField(blank=True, max_length=100, null=True, unique=True),
                ),
                ("idempotency_key", models.CharField(max_length=64, unique=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("last_event_at", models.DateTimeField(blank=True, null=True)),
                ("last_provider_event", models.CharField(blank=True, max_length=40)),
                ("first_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("lease_until", models.DateTimeField(blank=True, null=True)),
                ("generation", models.PositiveIntegerField(default=0)),
                ("payload_hash", models.CharField(blank=True, max_length=64)),
                ("is_test", models.BooleanField(default=False)),
                (
                    "form",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="forms.form"
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="submissions.submissionreview",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_notifications",
                        to="submissions.submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "correo",
                "verbose_name_plural": "correos",
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="EmailDeliveryEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("provider_event_id", models.CharField(max_length=100, unique=True)),
                ("provider_message_id", models.CharField(db_index=True, max_length=100)),
                ("event_type", models.CharField(max_length=40)),
                ("occurred_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "notification",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_events",
                        to="notifications.emailnotification",
                    ),
                ),
            ],
            options={
                "ordering": ["occurred_at", "pk"],
            },
        ),
        migrations.CreateModel(
            name="EmailSendAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("generation", models.PositiveIntegerField()),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(null=True)),
                ("status", models.CharField(default="SENDING", max_length=20)),
                ("error", models.CharField(blank=True, max_length=500)),
                (
                    "provider_message_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="send_attempts",
                        to="notifications.emailnotification",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="FormNotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("notify_internal_on_submission", models.BooleanField(default=True)),
                ("notify_respondent_on_validated", models.BooleanField(default=True)),
                ("notify_respondent_on_rejected", models.BooleanField(default=True)),
                ("respondent_email_stable_key", models.CharField(blank=True, max_length=100)),
                (
                    "form",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_settings",
                        to="forms.form",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="emailnotification",
            index=models.Index(
                fields=["status", "created_at"], name="notificatio_status_1d75ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailnotification",
            index=models.Index(
                fields=["event_type", "created_at"], name="notificatio_event_t_a506ef_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="emailnotification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "PENDING",
                            "SENDING",
                            "SENT",
                            "DELIVERED",
                            "DELIVERY_DELAYED",
                            "FAILED",
                            "BOUNCED",
                            "COMPLAINED",
                            "SUPPRESSED",
                            "SKIPPED",
                        ],
                    )
                ),
                name="notification_valid_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="emailsendattempt",
            constraint=models.UniqueConstraint(
                fields=("notification", "number"), name="notification_attempt_number"
            ),
        ),
    ]
