# Generated by Django 5.2.17 on 2026-09-25 23:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="formnotificationsettings",
            name="internal_recipients",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
